<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-26VH0J8" failures="1" tests="6" name="Surefire test" time="240.587" errors="0" timestamp="2024-03-21T17:49:45 IST">
  <testcase classname="UIAutomation.ErrorValidationTest" name="loginErrorValidation" time="0.772"/>
  <testcase classname="UIAutomation.ErrorValidationTest" name="productErrorValidation" time="14.499">
    <skipped/>
  </testcase> <!-- productErrorValidation -->
  <testcase classname="UIAutomation.ErrorValidationTest" name="productErrorValidation" time="14.159">
    <skipped/>
  </testcase> <!-- productErrorValidation -->
  <testcase classname="UIAutomation.ErrorValidationTest" name="productErrorValidation" time="14.336">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at UIAutomation.ErrorValidationTest.productErrorValidation(ErrorValidationTest.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- productErrorValidation -->
  <testcase classname="UIAutomation.SubmitOrderTest" name="submitOrder" time="15.143"/>
  <testcase classname="UIAutomation.SubmitOrderTest" name="verifyProductInOrderList" time="1.917"/>
</testsuite> <!-- Surefire test -->
