<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-26VH0J8" failures="1" tests="4" name="Error Validation" time="212.387" errors="0" timestamp="2024-03-24T10:31:07 IST">
  <testcase classname="UIAutomation.ErrorValidationTest" name="loginErrorValidation" time="20.633"/>
  <testcase classname="UIAutomation.ErrorValidationTest" name="productErrorValidation" time="14.317">
    <skipped/>
  </testcase> <!-- productErrorValidation -->
  <testcase classname="UIAutomation.ErrorValidationTest" name="productErrorValidation" time="14.324">
    <skipped/>
  </testcase> <!-- productErrorValidation -->
  <testcase classname="UIAutomation.ErrorValidationTest" name="productErrorValidation" time="14.193">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at UIAutomation.ErrorValidationTest.productErrorValidation(ErrorValidationTest.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- productErrorValidation -->
</testsuite> <!-- Error Validation -->
